# Generated by Django 2.2.10 on 2020-03-25 21:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_video', models.URLField()),
                ('instrucciones', models.CharField(max_length=500)),
                ('delivery_email', models.EmailField(max_length=254)),
                ('delivery_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('privacy_state', models.BooleanField(default=True, verbose_name='Privado')),
                ('from_person', models.CharField(max_length=30)),
                ('to_person', models.CharField(max_length=30)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aceptado'), (3, 'Rechazado'), (4, 'Realizado')], default=1)),
            ],
            options={
                'verbose_name': 'Cameo',
                'verbose_name_plural': 'Cameos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ocasion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Ocasion',
                'verbose_name_plural': 'Ocasiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('cameo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameos.Cameo')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['id'],
            },
        ),
    ]
