# Generated by Django 2.2.10 on 2020-03-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cameos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Client'),
        ),
        migrations.AddField(
            model_name='cameo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Client'),
        ),
        migrations.AddField(
            model_name='cameo',
            name='ocasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameos.Ocasion'),
        ),
        migrations.AddField(
            model_name='cameo',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Talent'),
        ),
    ]
