# Generated by Django 2.2.10 on 2020-03-25 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Biografía')),
                ('seguidores', models.IntegerField(verbose_name='Seguidores')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupación')),
                ('tiempo_respuesta', models.IntegerField()),
                ('ausente', models.BooleanField(default=False, verbose_name='Ausente')),
                ('categorias', models.ManyToManyField(to='talentos.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talento',
                'verbose_name_plural': 'Talentos',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('user_twitter', models.CharField(blank=True, max_length=30, null=True)),
                ('favoritos', models.ManyToManyField(blank=True, to='usuarios.Talent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
