# Generated by Django 2.2 on 2020-03-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200304_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclient',
            name='estado',
        ),
    ]
