# Generated by Django 2.2 on 2020-03-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0005_remove_talent_estado'),
        ('usuarios', '0003_remove_userclient_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoCuenta',
        ),
    ]
