# Generated by Django 2.2 on 2020-03-05 04:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_video', models.URLField()),
                ('instrucciones', models.CharField(max_length=500)),
                ('delivery_email', models.EmailField(max_length=254)),
                ('delivery_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('privacyState', models.BooleanField(default=True, verbose_name='Privado')),
                ('from_person', models.CharField(max_length=30)),
                ('to_person', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Cameo',
                'verbose_name_plural': 'Cameos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCameo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado Cameo',
                'verbose_name_plural': 'Estado Cameos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ocasion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Ocasion',
                'verbose_name_plural': 'Ocasiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Biografía')),
                ('seguidores', models.IntegerField(verbose_name='Seguidores')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupación')),
                ('tiempo_respuesta', models.IntegerField()),
                ('categorias', models.ManyToManyField(to='talentos.Category')),
            ],
            options={
                'verbose_name': 'Talento',
                'verbose_name_plural': 'Talentos',
                'ordering': ['id'],
            },
        ),
    ]
