# Generated by Django 2.2.10 on 2020-03-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cameo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cameos.Cameo'),
        ),
    ]
