# Generated by Django 2.2 on 2020-03-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('talentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.EstadoCuenta'),
        ),
        migrations.AddField(
            model_name='talent',
            name='talent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='cameo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentos.Cameo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cameo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentos.Cameo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.UserClient'),
        ),
        migrations.AddField(
            model_name='cameo',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talentos.EstadoCameo'),
        ),
        migrations.AddField(
            model_name='cameo',
            name='ocasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentos.Ocasion'),
        ),
        migrations.AddField(
            model_name='cameo',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentos.Talent'),
        ),
        migrations.AddField(
            model_name='cameo',
            name='userClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.UserClient'),
        ),
    ]
