# Generated by Django 2.2 on 2020-03-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0002_auto_20200304_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'verbose_name': 'Talento', 'verbose_name_plural': 'Talentos'},
        ),
    ]
