# Generated by Django 2.2 on 2020-03-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0003_auto_20200304_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameo',
            name='estado',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'Aceptado'), (3, 'Rechazado'), (4, 'Realizado')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='EstadoCameo',
        ),
    ]
