# Generated by Django 2.2 on 2020-03-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0004_auto_20200305_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='estado',
        ),
    ]
