# Generated by Django 2.2 on 2020-03-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0005_remove_talent_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='ausente',
            field=models.BooleanField(default=False, verbose_name='Ausente'),
        ),
    ]
